

resource "kubernetes_secret" "peercode_secret" {
  metadata {
    name      = "peercode-secret"
    namespace = "dev"
  }

  data = {
    MONGO_PEERCODE_DATABASE_NAME           = var.MONGO_PEERCODE_DATABASE_NAME
    MONGO_PEERCODE_DATABASE_PASSWORD       = var.MONGO_PEERCODE_DATABASE_PASSWORD
    MONGO_PEERCODE_DATABASE_USER           = var.MONGO_PEERCODE_DATABASE_USER
    MONGO_PEERCODE_HOST_NAME               = var.MONGO_PEERCODE_HOST_NAME
    MONGO_INITDB_ROOT_USERNAME             = var.MONGO_INITDB_ROOT_USERNAME
    MONGO_INITDB_ROOT_PASSWORD             = var.MONGO_INITDB_ROOT_PASSWORD
    MONGO_PEERCODE_URL                     = var.MONGO_PEERCODE_URL
    RABBITMQ_URL                           = var.RABBITMQ_URL
    RABBITMQ_DEFAULT_USER                  = var.RABBITMQ_DEFAULT_USER
    RABBITMQ_DEFAULT_PASS                  = var.RABBITMQ_DEFAULT_PASS
    OPENAI_API_KEY                         = var.OPENAI_API_KEY
    REACT_APP_FIREBASE_API_KEY             = var.REACT_APP_FIREBASE_API_KEY
    REACT_APP_FIREBASE_AUTH_DOMAIN         = var.REACT_APP_FIREBASE_AUTH_DOMAIN
    REACT_APP_FIREBASE_PROJECT_ID          = var.REACT_APP_FIREBASE_PROJECT_ID
    REACT_APP_FIREBASE_STORAGE_BUCKET      = var.REACT_APP_FIREBASE_STORAGE_BUCKET
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID = var.REACT_APP_FIREBASE_MESSAGING_SENDER_ID
    REACT_APP_FIREBASE_MEASUREMENT_ID      = var.REACT_APP_FIREBASE_MEASUREMENT_ID
  }

  type = "Opaque"
}
